import React from 'react'
import Image from 'next/image'
import image from '@/assets/guy_coding.png'

const About = () => {
  return (
    <section className='min-h-screen' id='about'>
      <div className='container flex justify-center items-center h-full'>
        <div className='py-12 text-center flex justify-center flex-col gap-5 items-center'>
          <h3 className='uppercase text-main font-bold text-3xl'>about me</h3>
          <p className='md:text-xl text-slate-700 md:w-8/12'>
            <span className='font-semibold text-slate-800'>Front-end Developer based in Algeria 📍.</span>
            <br /> My name is Emad, and I'm a Frontend Developer. My passion is to create and
            develop a clean UI/UX websites and apps for my users. <br />
            My main stack currently is <span className='font-semibold text-slate-800'>React/Next.js</span> in combination with Tailwind CSS and <span className='font-semibold text-slate-800'>TypeScript.</span>
          </p>
          <div>
            {/* Image generated by Dezgo AI */}
            <Image src={image} alt="the image generated with AI" />
            <span className='flex justify-end text-slate-800'>Generated with AI 🔮</span>
          </div>
          <div className='mt-3'>
            <div className='flex items-center gap-3'>
              <span>
                Tech Stack
              </span>
              <div className='bg-slate-400 w-0.5 h-5'></div>
              <div className='flex items-center flex-wrap gap-8'>
                <div>
                  <img src={'https://skillicons.dev/icons?i=html,css,tailwind'}  alt="html,css,tailwind" />
                </div>
                <div>
                  <img src={'https://skillicons.dev/icons?i=js,ts'}  alt="icons?i=js,ts" />
                </div>
                <div>
                  <img src={'https://skillicons.dev/icons?i=react,next'}  alt="react,next" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default About