export { default as HeroSection } from './HeroSection'
export { default as About } from './AboutSection'
export { default as Projects } from './ProjectsSection'
export { default as Contact } from './ContactSection'
export { default as SocialProf } from './SocialProf'